# Configuration for probot-stale - https://github.com/probot/stale
# Configuration options apply to both Issues and Pull Requests.
# We configure those individually to match our workflow (see `pulls:` and `issues:`)

pulls:
  # Number of days of inactivity before a Pull Request becomes stale
  daysUntilStale: 14

  # Number of days of inactivity before a Pull Request with the stale label is closed.
  # Set to false to disable. If disabled, Pull Request still need to be closed manually, but will remain marked as stale.
  daysUntilClose: 21

  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    If you would like us to be able to process this pull request, please provide the requested information or make the requested changes.
    If the information is not provided or the requested changes are not made within the next 3 weeks, we will be unable to proceed and this pull request will be closed.
  # Comment to post when closing a stale Pull Request.
  closeComment: >
    Closing due to lack of requested feedback.
    If you would like to proceed with your contribution, please provide the requested information or make the requested changes, and we will re-open this pull request.
issues:
  daysUntilStale: 14

  # Number of days of inactivity before an Issue with the stale label is closed.
  # Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
  daysUntilClose: 21

  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    If you would like us to be able to process this issue, please provide the requested information.
    If the information is not provided within the next 3 weeks, we will be unable to proceed and this issue will be closed.
  # Comment to post when closing a stale Issue.
  closeComment: >
    Closing due to lack of requested feedback.
    If you would like to proceed with your contribution, please provide the requested information and we will re-open this issue.

# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: ["status: waiting-for-feedback"]

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels: []

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

# Label to use when marking as stale
staleLabel: "status: stale"

# Comment to post when removing the stale label.
# unmarkComment: >
#   Your comment here.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
# only: issues
